name: Hello World

on:
  workflow_dispatch:
  
jobs:
  hello-world:
    name: Hello World Job
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Hello World"
      - run: ls -l
      - uses: actions/checkout@v3
      - run: ls -l
      - uses: advanced-security/generate-sbom-action@v1
      - run: cat sbom*.json
